version: 0.0
os: linux
files:
  - source: /
    destination: /root/grafana_configs
hooks:
  BeforeInstall:
    - location: pre_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: generate_and_deploy.sh
      timeout: 300
      runas: root
