version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y aws-cli
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - aws s3 ls s3://promtail-deploy-bucket/ || echo "S3 bucket is accessible"
      - echo "Cleaning up any existing temporary directories..."
      - rm -rf /tmp/promtail-configs  # Cleanup the directory if it exists
  build:
    commands:
      - echo "Building and packaging files..."
      - mkdir -p /tmp/promtail-configs  # Create the directory
      - cp -r * /tmp/promtail-configs  # Copy files to the directory
  post_build:
    commands:
      - echo "Uploading files to S3 bucket..."
      - aws s3 sync /tmp/promtail-configs s3://promtail-deploy-bucket/
artifacts:
  files:
    - '**/*'
cache:
  paths: []

